# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhipster8-boilerplate
services:
  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb
  elasticsearch:
    extends:
      file: ./elasticsearch.yml
      service: elasticsearch
